server:
  port: 8080
  context-path: /google-authenticator-server

spring:
  jpa:
    database: mysql
    hibernate:
      ddl-auto: create-drop
    show-sql: true
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/google_auth_server
    username: go-auth-server
    password: 123456


